# Generated by Django 2.1.1 on 2018-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_area_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='polygon',
            new_name='geometry',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
