# Generated by Django 2.1.1 on 2018-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('language', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
    ]
